mv usb设备.svg usbdevice.svg
mv 处理器.svg cpu.svg
mv 存储设备.svg storage.svg
mv 打印机.svg printer.svg
mv 电池.svg battery.svg
mv 概况.svg overview.svg
mv 键盘.svg keyboard.svg
mv 蓝牙.svg bluetooth.svg
mv 内存.svg memory.svg
mv 其他输入设备.svg otherinputdevice.svg
mv 其他PCI设备.svg otherpcidevice.svg
mv 鼠标.svg mouse.svg
mv 图像设备.svg camera.svg
mv 网络适配器.svg networkadapter.svg
mv 显示设备.svg monitor.svg
mv 显示适配器.svg displayadapter.svg
mv 音频适配器.svg audiodevice.svg
mv 主板.svg motherboard.svg
mv 光驱设备.svg cdrom.svg